repositories {
    mavenCentral()
    google() // Needed for androidx

    maven { url = 'https://maven.pedropathing.com' }
    maven { url = "https://mymaven.bylazar.com/releases" }
    maven { url = 'https://jitpack.io' }

    maven {
        url = "https://repo.dairy.foundation/releases"
    }

    maven {
        url = "https://repo.dairy.foundation/snapshots"
    }

    maven { url = 'https://maven.brott.dev/' }
}

dependencies {
    // FTC SDK 11.2.0
    implementation 'org.firstinspires.ftc:Inspection:11.2.0'
    implementation 'org.firstinspires.ftc:Blocks:11.2.0'
    implementation 'org.firstinspires.ftc:RobotCore:11.2.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.2.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.2.0'
    implementation 'org.firstinspires.ftc:Hardware:11.2.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.2.0'
    implementation 'org.firstinspires.ftc:Vision:11.2.0'

    // AndroidX
    implementation 'androidx.appcompat:appcompat:1.2.0'

    // FTC Dashboard
    implementation('com.acmerobotics.dashboard:dashboard:0.5.0') {
        exclude group: 'org.firstinspires.ftc'
    }

    // Homeostasis
    implementation 'com.github.Thermal-Equilibrium:homeostasis-FTC:1.0.8'

    // FTCLib
    implementation 'org.ftclib.ftclib:core:2.1.1'

    // Pedro Pathing
    implementation 'com.pedropathing:ftc:2.1.2'
    implementation 'com.pedropathing:telemetry:1.0.0'

    // Bylazar Panels
    implementation 'com.bylazar:fullpanels:1.0.12'
    implementation 'com.bylazar:graph:1.0.4'

    // TEMPORARILY DISABLED FOR TESTING
//     implementation("dev.frozenmilk.sinister:Sloth:0.2.4")
     implementation "dev.frozenmilk.dairy:CachingHardware:1.0.0"
}